- project:
    name: openstack/loci
    check:
      jobs:
        - loci-cinder
        #- loci-designate
        - loci-glance
        - loci-heat
        - loci-horizon
        - loci-ironic
        - loci-keystone
        #- loci-murano
        - loci-neutron
        - loci-nova
        - loci-requirements
        #- loci-swift
        #- loci-trove
    gate:
      jobs:
        - loci-cinder
        #- loci-designate
        - loci-glance
        - loci-heat
        - loci-horizon
        - loci-ironic
        - loci-keystone
        #- loci-murano
        - loci-neutron
        - loci-nova
        - loci-requirements
        #- loci-swift
        #- loci-trove
    post:
      jobs:
        - publish-loci-cinder
        #- publish-loci-designate
        - publish-loci-glance
        - publish-loci-heat
        - publish-loci-horizon
        - publish-loci-ironic
        - publish-loci-keystone
        #- publish-loci-murano
        - publish-loci-neutron
        - publish-loci-nova
        - publish-loci-requirements
        #- publish-loci-swift
        #- publish-loci-trove

- secret:
    name: loci_docker_login
    data:
      user: !encrypted/pkcs1-oaep
        - r8Nbpq5olmfLF035BZ/CUoFLIdhvBi/49KuochOAHbvns+xMiho3C7MEFzYDqJX3IhHde
          BICYOgK7qnyINOIZL2e7pl75rEdHQwJjSFUMkpdY6wEP7f9hpolj9xVp0ifHUVQqPHMRn
          zoPFd8MEAHxH5GLmc2SWJ98E/QUqGltxBi1YRSZoCcNtq3tHFK5Y+xQlLhIseJ2HkpDs6
          YXOGP9Qt4Va6sdyBcA90H+apSAcYA3Duu962ySZQAsYNui/3NQq3gLA+OZeyTJtcrh4hj
          Rb5dBnDWfSrMpxdNkbPXXgbQaxO3T0L4jbaOF8VKEsiI9olBrOeV2M9ddYJjSsHGj4XR8
          4vwS0+doB7np93fujiDuHVgdG8R40NW2GznyKRlRtzAORla7Mzw1Y1MokcUyY6p1LlLLl
          wUuWYCCEuRciOPhZXQ2u42qju/zrK2/dPnO8HfUINSrN0WbNq14ZwPpbj0ro02oGPbtwu
          OTw1z+N0Nc+GuLWlwYJGYM/z0UnvDR3WEBc2kXbVev9w4n0cB3RyphML2PDZZWbw8tjnX
          h1VsAOJ0Qo4qq1K/ft95ypd+vtjkfepEgHEBmJNwutJa9IHAkGfrkO9VkpUTPpfffnPwz
          d0/zaaadNl6MLQUSutRwY23YIIbv+fmukxw2vnJmvn6abkBlMya7KgtifwNA8c=
      password: !encrypted/pkcs1-oaep
        - gUEX4eY3JAk/Xt7Evmf/hF7xr6HpNRXTibZjrKTbmI4QYHlzEBrBbHey27Pt/eYvKKeKw
          hk8MDQ4rNX7ZK1v+CKTilUfOf4AkKYbe6JFDd4z+zIZ2PAA7ZedO5FY/OnqrG7nhLvQHE
          5nQrYwmxRp4O8eU5qG1dSrM9X+bzri8UnsI7URjqmEsIvlUqtybQKB9qQXT4d6mOeaKGE
          5h6Ydkb9Zdi4Qh+GpCGDYwHZKu1mBgVK5M1G6NFMy1DYz+4NJNkTRe9J+0TmWhQ/KZSqo
          4ck0x7Tb0Nr7hQzV8SxlwkaCTLDzvbiqmsJPLmzXY2jry6QsaRCpthS01vnj47itoZ/7p
          taH9CoJ0Gl7AkaxsrDSVjWSjatTQpsy1ub2fuzWHH4ASJFCiu83Lb2xwYts++r8ZSn+mA
          hbEs0GzPI6dIWg0u7aUsRWMOB4A+6t2IOJibVYwmwkG8TjHRXxVCLH5sY+i3MR+NicR9T
          IZFdY/AyH6vt5uHLQDU35+5n91pUG3F2lyiY5aeMOvBL05p27GTMuixR5ZoHcvSoHHtCq
          7Wnk21iHqmv/UnEzqUfXZOque9YP386RBWkshrHd0x3OHUfBK/WrpivxvIGBzGwMr2qAj
          /AhJsfDXKBBbhGOGk1u5oBLjeC4SRnAcIVh1+RWzR4/cAhOuy2EcbzxaGb6VTM=

- job:
    name: loci-base
    pre-run: playbooks/setup-gate
    run: playbooks/loci-builder
    post-run: playbooks/post
    timeout: 1200

- job:
    name: loci-cinder
    parent: loci-base
    vars:
      project: cinder
    required-projects:
      - openstack/loci
      - openstack/cinder

- job:
    name: publish-loci-cinder
    parent: loci-cinder
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-designate
    parent: loci-base
    vars:
      project: designate
    required-projects:
      - openstack/loci
      - openstack/designate

- job:
    name: publish-loci-designate
    parent: loci-designate
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-glance
    parent: loci-base
    vars:
      project: glance
    required-projects:
      - openstack/loci
      - openstack/glance

- job:
    name: publish-loci-glance
    parent: loci-glance
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-heat
    parent: loci-base
    vars:
      project: heat
    required-projects:
      - openstack/loci
      - openstack/heat

- job:
    name: publish-loci-heat
    parent: loci-heat
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-horizon
    parent: loci-base
    vars:
      project: horizon
    required-projects:
      - openstack/loci
      - openstack/horizon

- job:
    name: publish-loci-horizon
    parent: loci-horizon
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-ironic
    parent: loci-base
    vars:
      project: ironic
    required-projects:
      - openstack/loci
      - openstack/ironic

- job:
    name: publish-loci-ironic
    parent: loci-ironic
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-keystone
    parent: loci-base
    vars:
      project: keystone
    required-projects:
      - openstack/loci
      - openstack/keystone

- job:
    name: publish-loci-keystone
    parent: loci-keystone
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-murano
    parent: loci-base
    vars:
      project: murano
    required-projects:
      - openstack/loci
      - openstack/murano

- job:
    name: publish-loci-murano
    parent: loci-murano
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-neutron
    parent: loci-base
    vars:
      project: neutron
    required-projects:
      - openstack/loci
      - openstack/neutron

- job:
    name: publish-loci-neutron
    parent: loci-neutron
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-nova
    parent: loci-base
    vars:
      project: nova
    required-projects:
      - openstack/loci
      - openstack/nova

- job:
    name: publish-loci-nova
    parent: loci-nova
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-requirements
    parent: loci-base
    timeout: 2400
    vars:
      project: requirements
    required-projects:
      - openstack/loci
      - openstack/requirements

- job:
    name: publish-loci-requirements
    parent: loci-requirements
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-swift
    parent: loci-base
    vars:
      project: swift
    required-projects:
      - openstack/loci
      - openstack/swift

- job:
    name: publish-loci-swift
    parent: loci-swift
    post-run: playbooks/push
    secrets:
      - loci_docker_login

- job:
    name: loci-trove
    parent: loci-base
    vars:
      project: trove
    required-projects:
      - openstack/loci
      - openstack/trove

- job:
    name: publish-loci-trove
    parent: loci-trove
    post-run: playbooks/push
    secrets:
      - loci_docker_login
