- hosts: all
  tasks:
    - include_vars: vars.yaml

    - name: Copy logs
      synchronize:
        src: '/logs'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/logs/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs

    # NOTE(SamYaple): Unused right now
    - name: Extract wheels for tarball.o.o
      block:
        - command: "docker save -o /tmp/wheels-{{ item.name }}.img openstackloci/{{ project }}:master-{{ item.name }}"
          with_items: "{{ distros }}"
        - command: "{{ zuul.project.src_dir }}/scripts/fetch_wheels.py"
          environment:
            WHEELS: /tmp/wheels-{{ item.name }}.img
            WHEELS_DEST: "{{ zuul.executor.work_root }}/artifacts/{{ item.name }}.tar.gz"
          with_items: "{{ distros }}"
      become: True
      when: False

    - name: Push requirements to DockerHub
      block:
        - command: docker login -u {{ loci_docker_login.user }} -p {{ loci_docker_login.password }}
          no_log: True
        - command: docker push openstackloci/{{ project }}:master-{{ item.name }}
          with_items: "{{ distros }}"
      become: True
      when: loci_docker_login is defined
